In [29]:
import itertools
from mxnet import contrib, gluon, image, nd
import math
import numpy as np
import d2lzh as d2l

img = image.imread('data/catdog.jpg')
h, w = img.shape[0:2]
print(h, w)

561 728


In [47]:
def display_anchors(fmap_w, fmap_h, s):
    fmap = nd.zeros((1, 3, fmap_w, fmap_h))  # 前两维的取值不影响输出结果
    anchors = contrib.nd.MultiBoxPrior(fmap, sizes=s, ratios=[1, 2])
    print(anchors[0])
    bbox_scale = nd.array((w, h, w, h))
    d2l.show_bboxes(d2l.plt.imshow(img.asnumpy()).axes,
                    anchors[0] * bbox_scale)

In [48]:
display_anchors(2, 2, [0.3])


[[0.09999999 0.09999999 0.4        0.4       ]
 [0.03786796 0.14393398 0.46213204 0.35606602]
 [0.6        0.09999999 0.9        0.4       ]
 [0.53786796 0.14393398 0.96213204 0.35606602]
 [0.09999999 0.6        0.4        0.9       ]
 [0.03786796 0.64393395 0.46213204 0.85606605]
 [0.6        0.6        0.9        0.9       ]
 [0.53786796 0.64393395 0.96213204 0.85606605]]
<NDArray 8x4 @cpu(0)>
