使用卷积层代替全连接层
===

In [1]:
%load_ext watermark
%watermark -a 'Sebastian Raschka' -v -p torch

Sebastian Raschka 

CPython 3.6.9
IPython 7.9.0

torch 1.1.0


In [2]:
import torch

假设我们有一个$2 \times 2(b,c,h,w)$的输入图片

In [3]:
inputs = torch.tensor([[[[1., 2.],
                         [3., 4.]]]])

inputs.shape

torch.Size([1, 1, 2, 2])

全连接层就是有一个4维的输入特征图，得到一个2维的输出特征图，算法如下

In [18]:
fc = torch.nn.Linear(4, 2)

weights = torch.tensor([[1.1, 1.2, 1.3, 1.4],
                        [1.5, 1.6, 1.7, 1.8]])
bias = torch.tensor([1.9, 2.0])
fc.weight.data = weights
fc.bias.data = bias

In [7]:
torch.relu(fc(inputs.view(-1, 4)))

tensor([[14.9000, 19.0000]], grad_fn=<ReluBackward0>)

![images](images/05_07_001.png)

我们也可以用卷积层来实现同样的效果

In [21]:
conv = torch.nn.Conv2d(in_channels=1,
                       out_channels=2,
                       kernel_size=(2,2))
print(conv.weight.size())
print(conv.bias.size())

torch.Size([2, 1, 2, 2])
torch.Size([2])


In [22]:
conv.weight.data = weights.view(2, 1, 2, 2)
conv.bias.data = bias
torch.relu(conv(inputs))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)

![images](images/05_07_002.png)

In [23]:
conv = torch.nn.Conv2d(in_channels=4,
                       out_channels=2,
                       kernel_size=(1, 1))

conv.weight.data = weights.view(2, 4, 1, 1)
conv.bias.data = bias
torch.relu(conv(inputs.view(1, 4, 1, 1)))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)